version: '3.8'

services:
  db-empresa:
    image: postgres:15
    container_name: db_empresa
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Company
    ports:
      - "5434:5432"
    volumes:
      - departamento:/var/lib/postgresql/data
    networks:
      - employeemanager_net

volumes:
  funcionario:
  departamento:

networks:
  employeemanager_net:
    driver: bridge